@startuml
skinparam linestyle ortho
rectangle "A" as one
rectangle "B" as two
rectangle "C" as three
rectangle "D" as four

one -right-> two: message 1-->2
two -right-> three: message 2-->3
two --> four: message 2-->4
three -[hidden]- four
@enduml

@startuml
actor "Operator" as op
actor "Subscriber" as sub
node "HSS" as hss
node "SMDP+" as smdp

op -right-> smdp : 1: Place profile order
smdp -> op : 2: Return provisioning data
op -right-> hss : 3: Provision profile data
op -down-> sub : 4: Provide download info
sub -[norank]> smdp : 5: Request download
hss -[hidden]down-> smdp
@enduml

@startuml
actor Ator as "trabalhador : Funcionário\nProvedor de Internet"
boundary Visao as "formularioLogin : LoginForm"
control Controlador as "controladorUsuarios:\n UsersController"
entity Modelo as "BancoFuncionarios : Worker"

Ator - (Visao): "1: abrirFormulario()\n2: inserirDadosAutenticacao()\n12:fecharFormulario()\n<&arrow-right>"
Visao - Visao : "3: verificarDados()\n11: mostrarMensagem()\n<&loop-circular>"
(Visao) -- (Controlador) : "4: verificarLogin()\n6: verificarSenha()\n8: aumentarContador()\n9: obterGrupoUsuario()\n<&arrow-bottom>"
(Controlador) -left- (Modelo) : "5: selecionar()\n7: selecionar()\n9: selecionar()\n<&arrow-left>"

'Outros ícones de setas
'<&arrow-left>
'<&arrow-right>
'<&arrow-top>
'<&arrow-botto

@enduml